#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=18

boot() {
	ifconfig wlan0 up
	iwpriv wlan0 set_mib xcap=38
	iwpriv wlan0 set_mib pwrlevelCCK_A=2c2c2c2c2c2c2c2c2c2c2c2c2c2c
	iwpriv wlan0 set_mib pwrlevelCCK_B=2d2d2d2d2d2d2d2d2d2d2d2d2d2d
	iwpriv wlan0 set_mib pwrlevelHT40_1S_A=2d2d2d2d2d2d2d2d2d2d2d2d2d2d
	iwpriv wlan0 set_mib pwrlevelHT40_1S_B=2e2e2e2e2d2d2d2d2d2d2d2d2d2d
	ifconfig wlan0 down
}
