#!/bin/sh /etc/rc.common

START=400

USE_PROCD=1
PROG=/usr/share/check_cable_wan.sh

start_service() {
	procd_open_instance
	procd_set_param command ${PROG}
	procd_set_param respawn
	procd_close_instance
}
