#!/bin/sh /etc/rc.common

START=500

USE_PROCD=1
PROG=/usr/share/keepalive.sh

start_service() {
	procd_open_instance
	procd_set_param command ${PROG}
	procd_set_param respawn
	procd_close_instance
}
