#!/bin/sh

if [ "$ACTION" = add ]
then
	if [ "$INTERFACE" = wlan0 ] && [ ! -f /var/run/hostapdstats-wlan0.pid ]
	then
		hostapd_cli -i wlan0 -P /var/run/hostapdstats-wlan0.pid -a /usr/share/hostapdstats.sh -B
	fi

	if [ "$INTERFACE" = wlan1 ] && [ ! -f /var/run/hostapdstats-wlan1.pid ]
	then
		hostapd_cli -i wlan1 -P /var/run/hostapdstats-wlan1.pid -a /usr/share/hostapdstats.sh -B
	fi
elif [ "$ACTION" = remove ]
then
	if [ "$INTERFACE" = wlan0 ] && [ -f /var/run/hostapdstats-wlan0.pid ]
	then
		hostapdstats_pid=$(cat /var/run/hostapdstats-wlan0.pid)
		kill -9 $hostapdstats_pid
	fi

	if [ "$INTERFACE" = wlan1 ] && [ -f /var/run/hostapdstats-wlan1.pid ]
	then
		hostapdstats_pid=$(cat /var/run/hostapdstats-wlan1.pid)
		kill -9 $hostapdstats_pid
	fi
else
	exit 0
fi
