#!/bin/sh

[ "$(type -t hostapd_cli)" ] || exit 0

if [ "$ACTION" = add ]
then
	if [ "$INTERFACE" = wlan0 ]
	then
		/etc/init.d/hostapdstats_wlan0 start
	elif [ "$INTERFACE" = wlan1 ]
	then
		/etc/init.d/hostapdstats_wlan1 start
	fi
elif [ "$ACTION" = remove ]
then
	if [ "$INTERFACE" = wlan0 ]
	then
		/etc/init.d/hostapdstats_wlan0 stop
	elif [ "$INTERFACE" = wlan1 ]
	then
		/etc/init.d/hostapdstats_wlan1 stop
	fi
else
	exit 0
fi
