#!/bin/sh /etc/rc.common

. /usr/share/functions/device_functions.sh
if [ -e /usr/share/functions/custom_device.sh ]
then
	. /usr/share/functions/custom_device.sh
	. /usr/share/functions/network_functions.sh
fi

START=17

boot() {
	[ "$(type -t anlix_bootup_defaults)" ] && anlix_bootup_defaults

	if [ "$(type -t set_vlan_on_boot)" ]
	then
		update_vlan
	fi
}
