#!/bin/sh /etc/rc.common

START=9E

USE_PROCD=1
PROG=/usr/share/functions/collect_data.sh

start_service() {
  procd_open_instance
  procd_set_param command ${PROG}
  procd_set_param respawn
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  procd_set_param pidfile /var/run/collect_data.pid
  procd_close_instance
}
