#!/bin/sh /etc/rc.common

USE_PROCD=1
PROG=/usr/share/data_collecting.sh

start_service() {
  logger -t "DATA_COLLECTING" "starting"
  procd_open_instance
  procd_set_param command nice ${PROG}
  procd_set_param respawn
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  procd_set_param pidfile /var/run/data_collecting.pid
  procd_close_instance
}

# exit code is 0 if service is running, 1 otherwise.
service_running() {
  procd_running data_collecting
}

# writes to log if service is running. procd will stop the service anyway.
stop_service() {
  if service_running; then
    logger -t "DATA_COLLECTING" "stopping"
  fi
}

# prevents service from restarting if it is already running.
reload_service() {
  if ! service_running; then
    start
  fi
}