#!/bin/sh /etc/rc.common

USE_PROCD=1
PROG=/usr/share/data_collecting.sh

start_service() {
  procd_open_instance
  procd_set_param command nice ${PROG}
  procd_set_param respawn
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  procd_set_param pidfile /var/run/data_collecting.pid
  procd_close_instance
}
