#!/bin/sh /etc/rc.common

START=300

USE_PROCD=1
PROG=/usr/share/imalive.sh

start_service() {
  /usr/share/boot_setup.sh
  procd_open_instance
  procd_set_param command ${PROG}
  procd_set_param respawn
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  procd_set_param pidfile /var/run/imalive.pid
  procd_close_instance
}
