#!/bin/sh /etc/rc.common

START=A1

USE_PROCD=1
PROG="hostapd_cli -a /usr/share/hostapdstats.sh"

start_service() {
  procd_open_instance
  procd_set_param command ${PROG}
  procd_set_param respawn
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  procd_set_param pidfile /var/run/hostapdstats.pid
  procd_close_instance
}
