#!/bin/sh /etc/rc.common

. /usr/share/functions/device_functions.sh
. /usr/share/functions/network_functions.sh
. /usr/share/functions/wireless_functions.sh

START=9F
STOP=1F

USE_PROCD=1

param_list() {

  local _wifi_config="$(get_wifi_local_config)"
  [ "$(echo "$_wifi_config" | jsonfilter -e '@["local_state_24"]')" == "1" ] && ubus -t 15 wait_for hostapd.wlan0 2>/dev/null
  [ "$(is_5ghz_capable)" == "1" ] && [ "$(echo "$_wifi_config" | jsonfilter -e '@["local_state_50"]')" == "1" ] && ubus -t 15 wait_for hostapd.wlan1 2>/dev/null

  radios=$(ubus list | grep hostapd.wlan)
  BRIDGE_IP_ADDR=""
  while true
  do
    BRIDGE_IP_ADDR="$(get_lan_bridge_ipaddr)"
    valid_ip "$BRIDGE_IP_ADDR"
    _retstatus=$?
    if [ $_retstatus -eq 0 ]
    then
      break
    fi
    sleep 5
  done
  json_init
  json_add_string "iface_ip" "$BRIDGE_IP_ADDR"
  json_add_string "mac" "$(get_mac)"
  json_add_string "ssid" "$(echo "$_wifi_config" | jsonfilter -e '@["local_ssid_24"]')"
  json_add_string "ssid_5" "$(echo "$_wifi_config" | jsonfilter -e '@["local_ssid_50"]')"
  [ "$(is_mesh_capable)" ] && json_add_int "mesh_support" "1"
  json_add_int "mesh" "$(get_mesh_mode)"
  [ "$(get_mesh_master)" ] && json_add_string "master" "$(get_mesh_master)" 
  for i in $radios
  do 
    [ "${i: -1}" = "0" ] && tlan="2" || tlan="5"
    json_add_string "mac_ssid$tlan" "$(ubus call $i rrm_nr_get_own | jsonfilter -e '$.value[0]')"
    json_add_string "meshid$tlan" "$(ubus call $i rrm_nr_get_own | jsonfilter -e '$.value[2]')"
  done
  local _ifA="$(ifconfig mesh0 2>/dev/null)"
  [ $? == 0 ] && json_add_string "mac_mesh0" "$(echo "$_ifA"| awk '/HWaddr/{print tolower($NF)}')"
  _ifA="$(ifconfig mesh1 2>/dev/null)"
  [ $? == 0 ] && json_add_string "mac_mesh1" "$(echo "$_ifA"| awk '/HWaddr/{print tolower($NF)}')"
  _ifA="$(ifconfig br-lan 2>/dev/null)"
  [ $? == 0 ] && json_add_string "mac_bridge" "$(echo "$_ifA"| awk '/HWaddr/{print tolower($NF)}')"

  echo "$(json_dump)"
  json_cleanup
}

start_service() {
  procd_open_instance
  procd_set_param command minisapo 
  procd_append_param command "$(param_list)"
  procd_set_param respawn
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  procd_set_param pidfile /var/run/minisapo.pid
  procd_close_instance
}

reload_service()
{
  if service_running; then
    ubus call anlix_sapo set_msg "$(param_list)"
  else
    start
  fi
}
