#!/bin/sh /etc/rc.common

. /usr/share/libubox/jshn.sh
. /usr/share/functions/device_functions.sh

IDX_START=17
if [ ! -z "$FLM_SWCONFIG_BOOT_ORDER" ]
then
	IDX_START=$FLM_SWCONFIG_BOOT_ORDER
fi

START=$IDX_START

boot() {
	local _bridge_mode=""
	local _disable_lan_ports=""

	json_cleanup
	json_load_file /root/flashbox_config.json
	json_get_var _bridge_mode bridge_mode
	json_get_var _disable_lan_ports bridge_disable_switch
	json_close_object

	if [ "$_bridge_mode" = "y" ] && [ "$(type -t set_switch_bridge_mode)" ]
	then
		set_switch_bridge_mode "$_disable_lan_ports"
	fi
}
