#!/bin/sh /etc/rc.common

. /usr/share/libubox/jshn.sh
if [ -e /usr/share/functions/custom_device.sh ]
then
	. /usr/share/functions/custom_device.sh
else
	. /usr/share/functions/device_functions.sh
fi

if [ "$(type -t swconfig_boot_order)" ]
then
	START=$(swconfig_boot_order)
else
	START=17
fi

boot() {
	local _bridge_mode=""
	local _disable_lan_ports=""

	json_cleanup
	json_load_file /root/flashbox_config.json
	json_get_var _bridge_mode bridge_mode
	json_get_var _disable_lan_ports bridge_disable_switch
	json_close_object

	# ONLY RELEVANT TO TARGETS THAT SWITCH CONFIG BY UCI IS USELESS
	if [ "$_bridge_mode" = "y" ] && [ "$(type -t set_switch_bridge_mode_on_boot)" ]
	then
		set_switch_bridge_mode_on_boot "$_disable_lan_ports"
	fi
}
