#!/bin/sh

. /usr/share/functions/common_functions.sh

[ "$ACTION" = stratum ] || [ "$ACTION" = step ] || exit 0

# step and periodic
log "NTP" "Host synced date with offset: $offset"
echo "$offset" > /tmp/anlixntp
